### ISSUE TITLE
Device turn off do not work after update to homebridge 1.3.0

### ISSUE THREAD

**Issue by staryga** [bbriatte/homebridge-soundtouch-platform#31]
Setting the field:
        "pollingInterval": 2000
results the error:

[2/22/2021, 11:16:32 AM] [Bose] Restarting Process...
Initializing HAP-NodeJS v0.9.2-beta.7...
[2/22/2021, 11:16:33 AM] [Bose] Launched external bridge with PID 46861
[2/22/2021, 11:16:33 AM] Registering platform 'homebridge-soundtouch-platform.SoundTouchPlatform'
[2/22/2021, 11:16:33 AM] [Bose] Loaded homebridge-soundtouch-platform v1.4.1 successfully
[2/22/2021, 11:16:33 AM] Loaded 1 cached accessories from cachedAccessories.0E73F3142652.
Preparing Advertiser for 'Bose BB88' using ciao backend!
[2/22/2021, 11:16:33 AM] [Bose] Searching accessories...
Starting to advertise 'Bose BB88' using ciao backend!
[2/22/2021, 11:16:33 AM] Homebridge v1.3.1-beta.5 (Bose) is running on port 55807.
[2/22/2021, 11:16:38 AM] [Bose] [Lifestyle Salon] Found device
[2/22/2021, 11:16:38 AM] [Bose] [Lifestyle Salon] Found local source 'BLUETOOTH' with account '' on device
[2/22/2021, 11:16:38 AM] [Bose] [Lifestyle Salon] Found local source 'QPLAY' with account 'QPlay1UserName' on device
[2/22/2021, 11:16:38 AM] [Bose] [Lifestyle Salon] Found local source 'QPLAY' with account 'QPlay2UserName' on device
[2/22/2021, 11:16:38 AM] [Bose] [Lifestyle Salon] Device ready
[2/22/2021, 11:16:38 AM] [Bose] Finish searching accessories

/usr/local/lib/node_modules/homebridge-soundtouch-platform/src/sound-touch-accessory-wrapper.ts:167
        for(const preset of presets) {
                            ^
TypeError: Cannot read property 'length' of undefined
    at SoundTouchAccessoryWrapper.<anonymous> (/usr/local/lib/node_modules/homebridge-soundtouch-platform/src/sound-touch-accessory-wrapper.ts:167:29)
    at step (/usr/local/lib/node_modules/homebridge-soundtouch-platform/dist/sound-touch-accessory-wrapper.js:46:23)
    at Object.next (/usr/local/lib/node_modules/homebridge-soundtouch-platform/dist/sound-touch-accessory-wrapper.js:27:53)
    at fulfilled (/usr/local/lib/node_modules/homebridge-soundtouch-platform/dist/sound-touch-accessory-wrapper.js:18:58)
[2/22/2021, 11:16:40 AM] [Bose] Child bridge process ended
[2/22/2021, 11:16:40 AM] [Bose] Process Ended. Code: 1, Signal: null

romoving the
"pollingInterval": 2000,
makes the plugin work
the device is visible in Home app, the device can be turn ON, but cannot be tour OFF
it was working fine in homebridge 1.2.5

**Comment by Spy-1** [comment]
same here.
Device cannot be turned off by the plugin an (Soundtouch not reachable)

[27.2.2021, 07:40:32] [homebridge-soundtouch-platform] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.

**Comment by Spy-1** [comment]
push
