### ISSUE TITLE
Error: Can't find device using the name 'xxx' on your network

### ISSUE THREAD

**Issue by mensa84** [bbriatte/homebridge-soundtouch-platform#44]
Hello,

I get that error every few days or weeks in my Homebridge log and then my Bose SoundTouch Series II can't be controlled anymore by HomeKit/Homebridge but still by the Bose app.

Log:
```
[5/17/2022, 12:55:26 PM] [SoundTouch] Error: Can't find device using the name 'Badezimmer Radio' on your network
    at Object.apiNotFoundWithName (/usr/lib/node_modules/homebridge-soundtouch-platform/src/errors.ts:2:12)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-soundtouch-platform/src/sound-touch-device.ts:54:19)
    at step (/usr/lib/node_modules/homebridge-soundtouch-platform/dist/sound-touch-device.js:33:23)
    at Object.next (/usr/lib/node_modules/homebridge-soundtouch-platform/dist/sound-touch-device.js:14:53)
    at fulfilled (/usr/lib/node_modules/homebridge-soundtouch-platform/dist/sound-touch-device.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

What is the problem? I think my configuration should be correct, cause it is working most of the time.

Config:
```
{
    "platform": "SoundTouchPlatform",
    "name": "SoundTouch",
    "accessories": [
        {
            "name": "Badezimmer Radio",
            "room": "Badezimmer Radio",
            "verbose": true,
            "volume": {
                "onValue": 30,
                "mode": "speaker"
            }
        }
    ],
    "global": {
        "sources": [
            {
                "source": "AUX",
                "enabled": false
            },
            {
                "source": "QPLAY",
                "enabled": false
            }
        ],
        "presets": [
            {
                "index": 1,
                "enabled": true
            }
        ]
    }
}
```

The name in the Bose app is also "Badezimmer Radio". So my config is correct, right?

**Comment by woodjme** [comment]
@mensa84 by no means a good solution, however, I've found going to version 1.3.1 fixes this. The latest versions don't work for me with a named device or autodiscover.

**Comment by mensa84** [comment]
Sorry, I did not understand the first part of your answer. What do you mean?
I am currently on 1.4.1 that is the newest version, but the problem still exists. Do you have any solution please?
Or should I not use a name for the device?

**Comment by woodjme** [comment]
I’m suggesting you try an old version as the new version is broken. - worked for me anyway.

**Comment by mensa84** [comment]
Ok, thank you! It seems to work. However, I can not say for sure, since the problem has only occurred sporadically

**Comment by mensa84** [comment]
The problem was fixxed for around one week with v1.3.1.
Today the error is appearing again and I am still on v1.3.1 :(
Any help please?
