### ISSUE TITLE
Plugin crashes and forces Homebridge to restart

### ISSUE THREAD

**Issue by glampr** [bbriatte/homebridge-soundtouch-platform#47]
After the September Soundtouch 10 Bose speaker upgrade, the plugin very frequently crashes and forces the entire homebridge server to restart. When this happens, it's usually force restarting in an endless loop. This is the stacktrace from the logs

```
Error: Occured on device XXX: [{"value":1043,"name":"EVENT_IN_WRONG_STATE","severity":"Unknown","message":"NowPlaying not supported in current state: Inactive"}]
    at new APIErrors (/usr/lib/node_modules/homebridge-soundtouch-platform/node_modules/soundtouch-api/src/error.ts:8:9)
    at Function.APIErrors.fromElement (/usr/lib/node_modules/homebridge-soundtouch-platform/node_modules/soundtouch-api/src/error.ts:14:16)
    at Function.API._throwAPIErrors (/usr/lib/node_modules/homebridge-soundtouch-platform/node_modules/soundtouch-api/src/api.ts:178:29)
    at API.<anonymous> (/usr/lib/node_modules/homebridge-soundtouch-platform/node_modules/soundtouch-api/src/api.ts:211:13)
    at step (/usr/lib/node_modules/homebridge-soundtouch-platform/node_modules/soundtouch-api/dist/api.js:33:23)
    at Object.next (/usr/lib/node_modules/homebridge-soundtouch-platform/node_modules/soundtouch-api/dist/api.js:14:53)
    at fulfilled (/usr/lib/node_modules/homebridge-soundtouch-platform/node_modules/soundtouch-api/dist/api.js:5:58)
```

**Comment by Matze177** [comment]
Currently, I'm not even able to do an initial configuration. After enabling the plug-in with the simple "all devices" setting, homebridge crashes and enters the reboot loop.
